import type { ProductStoredRecord } from "@/lib/db";

const now = "2026-06-10T08:00:00.000Z";

function product(
  input: Omit<ProductStoredRecord, "createdAt" | "updatedAt" | "status" | "referencePrice" | "imageUrl">
): ProductStoredRecord {
  return {
    ...input,
    referencePrice: "询价为准",
    imageUrl: "",
    status: "DRAFT",
    createdAt: now,
    updatedAt: now
  };
}

export const productSeeds: ProductStoredRecord[] = [
  product({
    id: 1,
    categoryId: 1,
    brand: "3M",
    sku: "8511CN",
    nameZh: "8511CN 防颗粒物口罩",
    nameEn: "8511CN Particulate Respirator",
    summaryZh: "N95 防颗粒物口罩，目录说明特别适合湿热环境或长时间重体力劳动使用。",
    summaryEn: "N95 particulate respirator for hot, humid, or long-duration heavy-duty work.",
    subcategoryZh: "随弃式防颗粒物口罩",
    subcategoryEn: "Disposable particulate respirator",
    specs: "认证：美国 NIOSH N95 和中国 KN95\n包装：10个/盒，8盒/箱=80个\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 2,
    categoryId: 1,
    brand: "3M",
    sku: "8210CN",
    nameZh: "8210CN 防颗粒物口罩",
    nameEn: "8210CN Particulate Respirator",
    summaryZh: "用于建筑、矿山、铸造、木加工、电子、制药、物料处理及打磨等作业产生颗粒物的防护。",
    summaryEn: "Particulate respirator for construction, mining, foundry, woodworking, electronics, pharmaceutical, material handling, and grinding work.",
    subcategoryZh: "随弃式防颗粒物口罩",
    subcategoryEn: "Disposable particulate respirator",
    specs: "认证：美国 NIOSH N95 和中国 KN95\n包装：20个/盒，8盒/箱=160个\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 3,
    categoryId: 1,
    brand: "3M",
    sku: "8247CN",
    nameZh: "8247CN 减除有机蒸气异味及防颗粒物口罩",
    nameEn: "8247CN Particulate Respirator with Organic Vapor Relief",
    summaryZh: "用于颗粒物及有机蒸气异味的防护，可用于铸造、实验室、农业、石化、底漆、清洁等行业。",
    summaryEn: "Particulate respirator with organic vapor nuisance odor relief for foundry, laboratory, agriculture, petrochemical, primer, and cleaning applications.",
    subcategoryZh: "异味减除防颗粒物口罩",
    subcategoryEn: "Nuisance odor particulate respirator",
    specs: "认证：美国 NIOSH R95 和中国 KN95\n包装：20个/盒，6盒/箱=120个\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第8页",
    imageSourceUrl: "PDF第8页，待裁切单品高清图"
  }),
  product({
    id: 4,
    categoryId: 1,
    brand: "3M",
    sku: "9324CN+",
    nameZh: "9324CN+ 防颗粒物口罩",
    nameEn: "9324CN+ Particulate Respirator",
    summaryZh: "用于防护多种作业产生的颗粒物，同时符合欧洲 FFP2 和中国 KN95 标准；可折叠，适合湿热环境或长时间重体力劳动使用。",
    summaryEn: "Foldable particulate respirator meeting European FFP2 and China KN95 standards.",
    subcategoryZh: "Aura 系列防颗粒物口罩",
    subcategoryEn: "Aura particulate respirator",
    specs: "认证：中国 LA GB2626-2019 KN95；欧洲 EN 149:2001+A1:2009 FFP2\n包装：10个/盒，12盒/箱=120个\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第9页",
    imageSourceUrl: "PDF第9页，待裁切单品高清图"
  }),
  product({
    id: 5,
    categoryId: 1,
    brand: "3M",
    sku: "9541/9542",
    nameZh: "9541/9542 减除有机蒸气异味及防颗粒物口罩",
    nameEn: "9541/9542 Particulate Respirator with Organic Vapor Relief",
    summaryZh: "采用高效静电滤材及特效活性炭层，用于颗粒物及有机蒸气异味的防护，可用于石化、化工、金属冶炼及加工等行业。",
    summaryEn: "Particulate respirator with activated carbon layer for nuisance organic vapor relief.",
    subcategoryZh: "异味减除防颗粒物口罩",
    subcategoryEn: "Nuisance odor particulate respirator",
    specs: "防护：颗粒物及有机蒸气异味\n包装：25个/盒，10盒/箱=250个\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第11页",
    imageSourceUrl: "PDF第11页，待裁切单品高清图"
  }),
  product({
    id: 6,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H220A",
    nameZh: "3M PELTOR ProTac III 薄型耳罩",
    nameEn: "3M PELTOR ProTac III Slim Headset",
    summaryZh: "环境声音功能耳罩，目录标称 SNR 27dB、NRR 21dB。",
    summaryEn: "Level-dependent hearing protector with listed SNR 27 dB and NRR 21 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：27dB\nNRR：21dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 7,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H220P3E",
    nameZh: "3M PELTOR ProTac III 薄型头盔式耳罩",
    nameEn: "3M PELTOR ProTac III Slim Helmet-Attached Headset",
    summaryZh: "环境声音功能耳罩，头盔安装型，目录标称 SNR 26dB、NRR 19dB。",
    summaryEn: "Helmet-attached level-dependent hearing protector with listed SNR 26 dB and NRR 19 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：26dB\nNRR：19dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 8,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H221A",
    nameZh: "3M PELTOR ProTac III 耳罩",
    nameEn: "3M PELTOR ProTac III Headset",
    summaryZh: "环境声音功能耳罩，目录标称 SNR 32dB、NRR 26dB。",
    summaryEn: "Level-dependent hearing protector with listed SNR 32 dB and NRR 26 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：32dB\nNRR：26dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 9,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H221P3E",
    nameZh: "3M PELTOR ProTac III 头盔式耳罩",
    nameEn: "3M PELTOR ProTac III Helmet-Attached Headset",
    summaryZh: "环境声音功能耳罩，头盔安装型，目录标称 SNR 31dB、NRR 23dB。",
    summaryEn: "Helmet-attached level-dependent hearing protector with listed SNR 31 dB and NRR 23 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：31dB\nNRR：23dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 10,
    categoryId: 3,
    brand: "3M",
    sku: "MT15H7AWS6-111",
    nameZh: "3M PELTOR WS ProTac XPI 耳罩",
    nameEn: "3M PELTOR WS ProTac XPI Headset",
    summaryZh: "降噪通讯耳罩，目录标称 SNR 31dB、NRR 26dB。",
    summaryEn: "Noise-reducing communication headset with listed SNR 31 dB and NRR 26 dB.",
    subcategoryZh: "降噪通讯耳罩",
    subcategoryEn: "Communication earmuff",
    specs: "SNR：31dB\nNRR：26dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 11,
    categoryId: 5,
    brand: "3M",
    sku: "1114189",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：黑色\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 12,
    categoryId: 5,
    brand: "3M",
    sku: "1114190",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 M 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, M, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：M\n颜色：黑色\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 13,
    categoryId: 5,
    brand: "3M",
    sku: "1114191",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 L 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, L, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：L\n颜色：黑色\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 14,
    categoryId: 5,
    brand: "3M",
    sku: "1103587",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码黑灰色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Black/Grey",
    summaryZh: "带铝质背部 D 型环和铝质前胸 D 型环的背心式全身系带，适合需要胸部连接点的高处作业场景。",
    summaryEn: "Vest-style full body harness with aluminum dorsal and front chest D-rings.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：黑灰色\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 15,
    categoryId: 5,
    brand: "3M",
    sku: "1103590",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码橙灰色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Orange/Grey",
    summaryZh: "带铝质背部 D 型环和铝质前胸 D 型环的背心式全身系带，橙灰色配置。",
    summaryEn: "Vest-style full body harness with aluminum dorsal and front chest D-rings, orange/grey configuration.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：橙灰色\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 16,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "QD30",
    nameZh: "Quiet 可重复使用耳塞",
    nameEn: "Quiet Reusable Earplug",
    summaryZh: "免揉搓设计，方便配戴；波浪状外形设计更贴合耳道。",
    summaryEn: "Reusable earplug with no-roll design and contoured fit.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "产品描述：Quiet\n形状：钟型\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 17,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "SMF-30",
    nameZh: "SmartFit 可重复使用耳塞",
    nameEn: "SmartFit Reusable Earplug",
    summaryZh: "SmartFit 舒适材料技术可利用佩戴者体温逐渐改变耳塞外形，帮助贴合耳道。",
    summaryEn: "Reusable earplug using SmartFit material technology.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "特点：可拆卸尼龙耳塞线，带 HearPack 耳塞盒\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 18,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "FUS30-HP",
    nameZh: "Fusion 双材料可重复使用耳塞",
    nameEn: "Fusion Reusable Earplug",
    summaryZh: "Fusion 双材料设计，包含方便拿捏配戴的核心柱和提供佩戴舒适性的柔软侧翼。",
    summaryEn: "Dual-material reusable earplug with handling stem and soft flanges.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "产品描述：Fusion 大号（蓝色）\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 19,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "MACH1-R024W",
    nameZh: "Mach 1 耳罩",
    nameEn: "Mach 1 Earmuff",
    summaryZh: "经济型耳罩，为多种工作环境提供简单方便的听力防护；轻便设计。",
    summaryEn: "Lightweight economical earmuff for a range of work environments.",
    subcategoryZh: "隔音耳罩",
    subcategoryEn: "Earmuff",
    specs: "订货号：MACH1-R024W（浅灰白）\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第17页",
    imageSourceUrl: "PDF第17页，待裁切单品高清图"
  }),
  product({
    id: 20,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "R-01526",
    nameZh: "Impact 电子耳罩",
    nameEn: "Impact Electronic Earmuff",
    summaryZh: "Impact 系列电子耳罩具备主动脉冲噪音降噪功能，同时能放大人声，便于交流。",
    summaryEn: "Electronic earmuff with impulse noise reduction and voice amplification.",
    subcategoryZh: "电子耳罩",
    subcategoryEn: "Electronic earmuff",
    specs: "SNR：25dB\nNRR：22dB\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第17页",
    imageSourceUrl: "PDF第17页，待裁切单品高清图"
  }),
  product({
    id: 21,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "100005",
    nameZh: "SVP OTG 防雾款亚洲款一镜两用安全防护眼镜",
    nameEn: "SVP OTG Anti-Fog Safety Glasses",
    summaryZh: "可容纳多数生活近视镜，超宽容镜空间；镜腿 6 档角度调节、3 档长度调节。",
    summaryEn: "Over-the-glass safety eyewear with wide fit and adjustable temples.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜架及镜腿：黑色\n镜片：透明\n防刮擦：是\n防雾：加强\n使用环境：室内\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第21页",
    imageSourceUrl: "PDF第21页，待裁切单品高清图"
  }),
  product({
    id: 22,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "S99100CN",
    nameZh: "S99 安全防护眼镜透明款",
    nameEn: "S99 Clear Safety Glasses",
    summaryZh: "重量仅 22g 的超轻款聚碳酸酯安全眼镜，防雾镜片避免佩戴口罩或面罩时镜片起雾。",
    summaryEn: "Ultra-light polycarbonate safety eyewear with anti-fog lens.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜片：透明\n防刮擦：是\n防雾：是\n使用环境：室内\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第21页",
    imageSourceUrl: "PDF第21页，待裁切单品高清图"
  }),
  product({
    id: 23,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "100100",
    nameZh: "S200A 亚洲款防冲击眼镜透明款",
    nameEn: "S200A Asian Fit Clear Impact Safety Glasses",
    summaryZh: "专为亚洲人设计，柔软鼻垫和镜腿提供舒适保护，一体式全景镜片设计提供宽阔视野。",
    summaryEn: "Asian-fit impact safety eyewear with soft nose pad, temples, and panoramic lens.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜架及镜腿：蓝色\n镜片：透明\n防刮擦：是\n防雾：是\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第22页",
    imageSourceUrl: "PDF第22页，待裁切单品高清图"
  }),
  product({
    id: 24,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "200500",
    nameZh: "LG200A 防护眼罩防雾款",
    nameEn: "LG200A Anti-Fog Safety Goggles",
    summaryZh: "通风孔可关闭，开启时为间接通风；超大防护面积镜片，可选装光学 RX 镜架。",
    summaryEn: "Safety goggles with closable indirect vents and optional RX insert frame.",
    subcategoryZh: "防冲击眼罩",
    subcategoryEn: "Safety goggles",
    specs: "产品描述：透明镜身/布质头带/镜片防雾\n镜片：透明 PC 镜片\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第30页",
    imageSourceUrl: "PDF第30页，待裁切单品高清图"
  }),
  product({
    id: 25,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "1017750pro",
    nameZh: "DuraMaxx 护目镜布质头带款",
    nameEn: "DuraMaxx Goggles with Fabric Headband",
    summaryZh: "镜片可更换，可增配 RX 矫视支架，能匹配霍尼韦尔半面罩；符合 ANSI Z87.1 防液体泼溅 D3 级别。",
    summaryEn: "Replaceable-lens safety goggles compatible with RX insert and Honeywell half masks.",
    subcategoryZh: "防冲击眼罩",
    subcategoryEn: "Safety goggles",
    specs: "镜架及头带：蓝灰色本体，织物头带\n防雾：Hydroshield 超强\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第31页",
    imageSourceUrl: "PDF第31页，待裁切单品高清图"
  }),
  product({
    id: 26,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "ACH2W80100ML",
    nameZh: "Aircore H2 全身式安全带 M/L",
    nameEn: "Aircore H2 Full Body Harness M/L",
    summaryZh: "标准配置重量仅 3.16kg，比同类产品轻 17%；全铝合金挂点及搭扣。",
    summaryEn: "Lightweight full body harness with aluminum alloy attachment points and buckles.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：M/L\n符合标准：EN361:2002、EN358:1999、EN1497:2007、GB6095、LA认证\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图"
  }),
  product({
    id: 27,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1002849A",
    nameZh: "DuraFlex 双挂点全身式安全带",
    nameEn: "DuraFlex Two-Point Full Body Harness",
    summaryZh: "弹性织带带来更好的舒适性和耐用性，搭扣式胸带扣和腿带扣，胸前织带环。",
    summaryEn: "Two-point full body harness with elastic webbing and front web loop.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：双挂点全身式安全带\n符合标准：GB6095\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图"
  }),
  product({
    id: 28,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1002853A",
    nameZh: "DuraFlex 双挂点全身式安全带金属环款",
    nameEn: "DuraFlex Two-Point Full Body Harness with Metal Front Ring",
    summaryZh: "弹性织带，带背部 D 型环和胸前部金属环，符合 GB6095。",
    summaryEn: "DuraFlex harness with dorsal D-ring and metal front ring.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：双挂点全身式安全带\n符合标准：GB6095\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图"
  }),
  product({
    id: 29,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1011890A",
    nameZh: "Titan 单挂点全身式安全带",
    nameEn: "Titan Single-Point Full Body Harness",
    summaryZh: "全身式可调节设计，一个规格适合多种身形；可滑动背部 D 型环，耐用聚酯织带。",
    summaryEn: "Adjustable single-point full body harness with sliding dorsal D-ring.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：Titan 单挂点全身式安全带\n符合标准：GB6095\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第114页",
    imageSourceUrl: "PDF第114页，待裁切单品高清图"
  }),
  product({
    id: 30,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1011891A",
    nameZh: "Titan 双挂点全身式安全带",
    nameEn: "Titan Two-Point Full Body Harness",
    summaryZh: "全身式可调节设计，带背部 D 型环和胸前部双 D 环。",
    summaryEn: "Adjustable two-point full body harness with dorsal D-ring and front dual D-rings.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：Titan 双挂点全身式安全带\n符合标准：GB6095\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第114页",
    imageSourceUrl: "PDF第114页，待裁切单品高清图"
  }),
  product({
    id: 31,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120784",
    nameZh: "Advantage 200LS 半面罩呼吸器小号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Small",
    summaryZh: "热塑材料小号半面罩，配套使用 Advantage 系列滤片；符合 GB2890 和 NIOSH 标准。",
    summaryEn: "Thermoplastic half-mask respirator for Advantage filters, small size.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，小号\n标准：GB2890、NIOSH\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 32,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120785",
    nameZh: "Advantage 200LS 半面罩呼吸器中号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Medium",
    summaryZh: "热塑材料中号半面罩，采用 MultiFlex 设计，佩戴时接触面压力均匀。",
    summaryEn: "Thermoplastic half-mask respirator with MultiFlex design, medium size.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，中号\n标准：GB2890、NIOSH\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 33,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120786",
    nameZh: "Advantage 200LS 半面罩呼吸器大号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Large",
    summaryZh: "热塑材料大号半面罩，轻巧柔软，低轮廓设计便于与眼镜、眼罩或耳罩搭配。",
    summaryEn: "Thermoplastic half-mask respirator, large size, with low-profile design.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，大号\n标准：GB2890、NIOSH\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 34,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10147997",
    nameZh: "Advantage 3100 全面罩呼吸器中号",
    nameEn: "Advantage 3100 Full-Facepiece Respirator, Medium",
    summaryZh: "热塑材料中号全面罩，内置口鼻罩，聚碳酸酯透镜视野宽阔，面屏带防刮镀层。",
    summaryEn: "Full-facepiece respirator with thermoplastic body and polycarbonate lens, medium size.",
    subcategoryZh: "全面罩呼吸器",
    subcategoryEn: "Full-facepiece respirator",
    specs: "产品描述：热塑材料，中号\n标准：GB2890、NIOSH\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 35,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10081114",
    nameZh: "OptimAir TL 动力送风过滤式呼吸器主机",
    nameEn: "OptimAir TL PAPR Blower Unit",
    summaryZh: "NIOSH 认证动力送风过滤式呼吸器主机，可配套送风头罩和全面罩，帮助防护颗粒物、有毒气体和有机蒸气。",
    summaryEn: "PAPR blower unit for use with loose-fitting hoods and tight-fitting full facepieces.",
    subcategoryZh: "动力送风过滤式呼吸器",
    subcategoryEn: "PAPR",
    specs: "产品编号：10081114\n符合：GB30864\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第10页",
    imageSourceUrl: "PDF第10页，待裁切单品高清图"
  }),
  product({
    id: 36,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10240493",
    nameZh: "M8-1800 正压式消防空气呼吸器 6.8L 有表瓶阀网状头带",
    nameEn: "M8-1800 SCBA 6.8L with Gauge Valve and Mesh Head Harness",
    summaryZh: "M8-1800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，有表瓶阀，G1 全面罩 Fix-PTC 中号网状头带配置。",
    summaryEn: "M8-1800 SCBA configuration with 6.8L cylinder, gauge valve, and G1 medium facepiece.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n面罩：G1 全面罩 Fix-PTC，中号，网状头带\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图"
  }),
  product({
    id: 37,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10240494",
    nameZh: "M8-1800 正压式消防空气呼吸器 6.8L 无表瓶阀网状头带",
    nameEn: "M8-1800 SCBA 6.8L without Gauge Valve, Mesh Head Harness",
    summaryZh: "M8-1800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，无表瓶阀，G1 全面罩 Fix-PTC 中号网状头带配置。",
    summaryEn: "M8-1800 SCBA configuration with 6.8L cylinder without gauge valve and G1 medium facepiece.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n面罩：G1 全面罩 Fix-PTC，中号，网状头带\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图"
  }),
  product({
    id: 38,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10241461",
    nameZh: "M8-2800 正压式消防空气呼吸器 6.8L 有表限流瓶阀",
    nameEn: "M8-2800 SCBA 6.8L with Gauge Flow-Limiting Valve",
    summaryZh: "M8-2800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，有表限流瓶阀，PR18C 减压器配置。",
    summaryEn: "M8-2800 SCBA with 6.8L cylinder, gauge flow-limiting valve, and PR18C reducer.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n减压器：PR18C\n面罩：G1 面罩 Fix-PTC，中号，网状头带\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 39,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10241462",
    nameZh: "M8-2800 正压式消防空气呼吸器 6.8L 无表限流瓶阀",
    nameEn: "M8-2800 SCBA 6.8L without Gauge Flow-Limiting Valve",
    summaryZh: "M8-2800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，无表限流瓶阀，PR18C 减压器配置。",
    summaryEn: "M8-2800 SCBA with 6.8L cylinder without gauge flow-limiting valve and PR18C reducer.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n减压器：PR18C\n面罩：G1 面罩 Fix-PTC，中号，网状头带\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 40,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10242202",
    nameZh: "G1 全面罩 Fix-PTC 接口中号网状头带",
    nameEn: "G1 Full Facepiece Fix-PTC, Medium, Mesh Head Harness",
    summaryZh: "G1 全面罩销售单元，Fix-PTC 接口，中号，网状头带，可作为 M8 系列空呼配置面罩。",
    summaryEn: "G1 full facepiece sales unit with Fix-PTC interface, medium size, mesh head harness.",
    subcategoryZh: "消防空气呼吸器面罩",
    subcategoryEn: "SCBA facepiece",
    specs: "接口：Fix-PTC\n尺码：中号\n头带：网状头带\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图"
  }),
  product({
    id: 41,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "ULTIMA X5000",
    nameZh: "ULTIMA X5000 气体探测器",
    nameEn: "ULTIMA X5000 Universal Gas Detector",
    summaryZh: "统一平台气体探测器，集成电化学、催化燃烧、红外吸收等检测技术，支持双探头灵活组合。",
    summaryEn: "Universal gas detector platform integrating electrochemical, catalytic bead, and infrared technologies.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "通讯：HART、Modbus RS485、无线 HART\n特点：OLED 显示、触摸屏、TruCal 智能传感技术\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第79页",
    imageSourceUrl: "PDF第79页，待裁切单品高清图"
  }),
  product({
    id: 42,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "PrimaX P/I",
    nameZh: "PrimaX P/I 气体探测器",
    nameEn: "PrimaX P/I Gas Detector",
    summaryZh: "PrimaX P 隔爆型可检测可燃性气体、有毒气体和氧气；PrimaX I 本安型采用电化学原理检测毒气和氧气。",
    summaryEn: "PrimaX P/I gas detector for combustible, toxic gas, and oxygen monitoring.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "认证：CCC、CPA、Ex、ATEX/IECEx、SIL2、EAC\n输出：4-20mA，HART 和继电器可选\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 43,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "PrimaX IR",
    nameZh: "PrimaX IR 系列红外可燃气体探测器",
    nameEn: "PrimaX IR Combustible Gas Detector",
    summaryZh: "采用高性能红外传感器，双重红外光源冗余设计，T90 小于 5 秒。",
    summaryEn: "Infrared combustible gas detector with redundant IR sources and T90 under 5 seconds.",
    subcategoryZh: "红外可燃气体探测器",
    subcategoryEn: "Infrared combustible gas detector",
    specs: "工作温度：-40℃至+70℃\n认证：CCC、CPA、SIL2、Ex d IIC T4\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 44,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "DF-8500SIL",
    nameZh: "DF-8500SIL 气体探测器",
    nameEn: "DF-8500SIL Gas Detector",
    summaryZh: "采用催化燃烧以及电化学原理，可检测可燃性气体和有毒有害气体。",
    summaryEn: "Gas detector using catalytic bead and electrochemical technologies.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "防护等级：IP66/IP67\n认证：CCC、CPA、Ex、CCS、SIL2\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 45,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "FlameGard 5 MSIR",
    nameZh: "FlameGard 5 MSIR 四频红外火焰探测器",
    nameEn: "FlameGard 5 MSIR Multi-Spectrum InfraRed Flame Detector",
    summaryZh: "四频红外火焰探测器，采用 ANN 智能神经元网络技术，有效区分真实火焰与干扰源。",
    summaryEn: "Multi-spectrum infrared flame detector with ANN technology.",
    subcategoryZh: "火焰探测器",
    subcategoryEn: "Flame detector",
    specs: "典型响应时间：5秒\n最远检测距离：70米\n认证：ATEX/IECEx、CSA、FM、UL、CCC、SIL3\n状态：草稿，待核对单品高清图后发布",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第81页",
    imageSourceUrl: "PDF第81页，待裁切单品高清图"
  })
];
