import type { ProductRecord, ProductStoredRecord } from "@/lib/db";

const now = "2026-06-10T08:00:00.000Z";

function product(
  input: Omit<ProductStoredRecord, "createdAt" | "updatedAt" | "status" | "referencePrice" | "imageUrl" | "images"> & {
    imageUrl?: string;
    images?: string[];
    status?: ProductRecord["status"];
  }
): ProductStoredRecord {
  const images = input.images || (input.imageUrl ? [input.imageUrl] : []);

  return {
    ...input,
    referencePrice: "询价为准",
    imageUrl: input.imageUrl || images[0] || "",
    images,
    status: input.status || "PUBLISHED",
    createdAt: now,
    updatedAt: now
  };
}

export const productSeeds: ProductStoredRecord[] = [
  product({
    id: 1,
    categoryId: 1,
    brand: "3M",
    sku: "8511CN",
    nameZh: "8511CN 防颗粒物口罩",
    nameEn: "8511CN Particulate Respirator",
    summaryZh: "N95 防颗粒物口罩，目录说明特别适合湿热环境或长时间重体力劳动使用。",
    summaryEn: "N95 particulate respirator for hot, humid, or long-duration heavy-duty work.",
    subcategoryZh: "随弃式防颗粒物口罩",
    subcategoryEn: "Disposable particulate respirator",
    specs: "认证：美国 NIOSH N95 和中国 KN95\n包装：10个/盒，8盒/箱=80个\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 2,
    categoryId: 1,
    brand: "3M",
    sku: "8210CN",
    nameZh: "8210CN 防颗粒物口罩",
    nameEn: "8210CN Particulate Respirator",
    summaryZh: "用于建筑、矿山、铸造、木加工、电子、制药、物料处理及打磨等作业产生颗粒物的防护。",
    summaryEn: "Particulate respirator for construction, mining, foundry, woodworking, electronics, pharmaceutical, material handling, and grinding work.",
    subcategoryZh: "随弃式防颗粒物口罩",
    subcategoryEn: "Disposable particulate respirator",
    specs: "认证：美国 NIOSH N95 和中国 KN95\n包装：20个/盒，8盒/箱=160个\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 3,
    categoryId: 1,
    brand: "3M",
    sku: "8247CN",
    nameZh: "8247CN 减除有机蒸气异味及防颗粒物口罩",
    nameEn: "8247CN Particulate Respirator with Organic Vapor Relief",
    summaryZh: "用于颗粒物及有机蒸气异味的防护，可用于铸造、实验室、农业、石化、底漆、清洁等行业。",
    summaryEn: "Particulate respirator with organic vapor nuisance odor relief for foundry, laboratory, agriculture, petrochemical, primer, and cleaning applications.",
    subcategoryZh: "异味减除防颗粒物口罩",
    subcategoryEn: "Nuisance odor particulate respirator",
    specs: "认证：美国 NIOSH R95 和中国 KN95\n包装：20个/盒，6盒/箱=120个\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第8页",
    imageSourceUrl: "PDF第8页，待裁切单品高清图"
  }),
  product({
    id: 4,
    categoryId: 1,
    brand: "3M",
    sku: "9334CN+",
    nameZh: "9334CN+ 防颗粒物口罩",
    nameEn: "9334CN+ Particulate Respirator",
    summaryZh: "用于对高毒颗粒物及焊接作业时金属烟的防护，过滤效率 99% 以上；可折叠，适合湿热环境或长时间重体力劳动使用。",
    summaryEn: "Foldable FFP3 particulate respirator for high-toxicity particles and welding metal fumes.",
    subcategoryZh: "Aura 系列防颗粒物口罩",
    subcategoryEn: "Aura particulate respirator",
    specs: "认证：中国 LA GB2626-2019 KN95；欧洲 EN 149:2001+A1:2009 FFP3\n包装：10个/盒，12盒/箱=120个\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第9页",
    imageSourceUrl: "PDF第9页，待裁切单品高清图",
    imageUrl: "/product-images/featured/3m-9334cn-plus.jpg",
    images: [
      "/product-images/featured/3m-9334cn-plus.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 5,
    categoryId: 1,
    brand: "3M",
    sku: "9541/9542",
    nameZh: "9541/9542 减除有机蒸气异味及防颗粒物口罩",
    nameEn: "9541/9542 Particulate Respirator with Organic Vapor Relief",
    summaryZh: "采用高效静电滤材及特效活性炭层，用于颗粒物及有机蒸气异味的防护，可用于石化、化工、金属冶炼及加工等行业。",
    summaryEn: "Particulate respirator with activated carbon layer for nuisance organic vapor relief.",
    subcategoryZh: "异味减除防颗粒物口罩",
    subcategoryEn: "Nuisance odor particulate respirator",
    specs: "防护：颗粒物及有机蒸气异味\n包装：25个/盒，10盒/箱=250个\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第11页",
    imageSourceUrl: "PDF第11页，待裁切单品高清图"
  }),
  product({
    id: 6,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H220A",
    nameZh: "3M PELTOR ProTac III 薄型耳罩",
    nameEn: "3M PELTOR ProTac III Slim Headset",
    summaryZh: "环境声音功能耳罩，目录标称 SNR 27dB、NRR 21dB。",
    summaryEn: "Level-dependent hearing protector with listed SNR 27 dB and NRR 21 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：27dB\nNRR：21dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 7,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H220P3E",
    nameZh: "3M PELTOR ProTac III 薄型头盔式耳罩",
    nameEn: "3M PELTOR ProTac III Slim Helmet-Attached Headset",
    summaryZh: "环境声音功能耳罩，头盔安装型，目录标称 SNR 26dB、NRR 19dB。",
    summaryEn: "Helmet-attached level-dependent hearing protector with listed SNR 26 dB and NRR 19 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：26dB\nNRR：19dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 8,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H221A",
    nameZh: "3M PELTOR ProTac III 耳罩",
    nameEn: "3M PELTOR ProTac III Headset",
    summaryZh: "环境声音功能耳罩，目录标称 SNR 32dB、NRR 26dB。",
    summaryEn: "Level-dependent hearing protector with listed SNR 32 dB and NRR 26 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：32dB\nNRR：26dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 9,
    categoryId: 3,
    brand: "3M",
    sku: "MT13H221P3E",
    nameZh: "3M PELTOR ProTac III 头盔式耳罩",
    nameEn: "3M PELTOR ProTac III Helmet-Attached Headset",
    summaryZh: "环境声音功能耳罩，头盔安装型，目录标称 SNR 31dB、NRR 23dB。",
    summaryEn: "Helmet-attached level-dependent hearing protector with listed SNR 31 dB and NRR 23 dB.",
    subcategoryZh: "环境声音功能耳罩",
    subcategoryEn: "Level-dependent earmuff",
    specs: "SNR：31dB\nNRR：23dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 10,
    categoryId: 3,
    brand: "3M",
    sku: "MT15H7AWS6-111",
    nameZh: "3M PELTOR WS ProTac XPI 耳罩",
    nameEn: "3M PELTOR WS ProTac XPI Headset",
    summaryZh: "降噪通讯耳罩，目录标称 SNR 31dB、NRR 26dB。",
    summaryEn: "Noise-reducing communication headset with listed SNR 31 dB and NRR 26 dB.",
    subcategoryZh: "降噪通讯耳罩",
    subcategoryEn: "Communication earmuff",
    specs: "SNR：31dB\nNRR：26dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第71页",
    imageSourceUrl: "PDF第71页，待裁切单品高清图"
  }),
  product({
    id: 11,
    categoryId: 5,
    brand: "3M",
    sku: "1114189",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：黑色\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图",
    imageUrl: "/product-images/featured/3m-exofit-light-1114189.jpg",
    images: [
      "/product-images/featured/3m-exofit-light-1114189.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 12,
    categoryId: 5,
    brand: "3M",
    sku: "1114190",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 M 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, M, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：M\n颜色：黑色\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图",
    imageUrl: "/product-images/featured/3m-exofit-light-1114190.jpg",
    images: [
      "/product-images/featured/3m-exofit-light-1114190.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 13,
    categoryId: 5,
    brand: "3M",
    sku: "1114191",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 L 码黑色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, L, Black",
    summaryZh: "背心式全身系带，配置铝质背部 D 型环、安全绳挂扣、快插带扣、旋钮式上身调节、标签保护套和冲击指示器。",
    summaryEn: "Vest-style full body harness with aluminum dorsal D-ring, lanyard keeper, quick-connect buckles, torso adjuster, label cover, and impact indicator.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：L\n颜色：黑色\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图",
    imageUrl: "/product-images/featured/3m-exofit-light-1114191.jpg",
    images: [
      "/product-images/featured/3m-exofit-light-1114191.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 14,
    categoryId: 5,
    brand: "3M",
    sku: "1103587",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码黑灰色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Black/Grey",
    summaryZh: "带铝质背部 D 型环和铝质前胸 D 型环的背心式全身系带，适合需要胸部连接点的高处作业场景。",
    summaryEn: "Vest-style full body harness with aluminum dorsal and front chest D-rings.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：黑灰色\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图",
    imageUrl: "/product-images/featured/3m-exofit-light-1103587.jpg",
    images: [
      "/product-images/featured/3m-exofit-light-1103587.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 15,
    categoryId: 5,
    brand: "3M",
    sku: "1103590",
    nameZh: "DBI-SALA ExoFit Light 全身式系带 S 码橙灰色",
    nameEn: "DBI-SALA ExoFit Light Full Body Harness, S, Orange/Grey",
    summaryZh: "带铝质背部 D 型环和铝质前胸 D 型环的背心式全身系带，橙灰色配置。",
    summaryEn: "Vest-style full body harness with aluminum dorsal and front chest D-rings, orange/grey configuration.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：S\n颜色：橙灰色\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M个人安全防护产品目录2025版，第128页",
    imageSourceUrl: "PDF第128页，待裁切单品高清图"
  }),
  product({
    id: 16,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "QD30",
    nameZh: "Quiet 可重复使用耳塞",
    nameEn: "Quiet Reusable Earplug",
    summaryZh: "免揉搓设计，方便配戴；波浪状外形设计更贴合耳道。",
    summaryEn: "Reusable earplug with no-roll design and contoured fit.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "产品描述：Quiet\n形状：钟型\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 17,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "SMF-30",
    nameZh: "SmartFit 可重复使用耳塞",
    nameEn: "SmartFit Reusable Earplug",
    summaryZh: "SmartFit 舒适材料技术可利用佩戴者体温逐渐改变耳塞外形，帮助贴合耳道。",
    summaryEn: "Reusable earplug using SmartFit material technology.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "特点：可拆卸尼龙耳塞线，带 HearPack 耳塞盒\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 18,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "FUS30-HP",
    nameZh: "Fusion 双材料可重复使用耳塞",
    nameEn: "Fusion Reusable Earplug",
    summaryZh: "Fusion 双材料设计，包含方便拿捏配戴的核心柱和提供佩戴舒适性的柔软侧翼。",
    summaryEn: "Dual-material reusable earplug with handling stem and soft flanges.",
    subcategoryZh: "可重复使用耳塞",
    subcategoryEn: "Reusable earplug",
    specs: "产品描述：Fusion 大号（蓝色）\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 19,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "MACH1-R024W",
    nameZh: "Mach 1 耳罩",
    nameEn: "Mach 1 Earmuff",
    summaryZh: "经济型耳罩，为多种工作环境提供简单方便的听力防护；轻便设计。",
    summaryEn: "Lightweight economical earmuff for a range of work environments.",
    subcategoryZh: "隔音耳罩",
    subcategoryEn: "Earmuff",
    specs: "订货号：MACH1-R024W（浅灰白）\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第17页",
    imageSourceUrl: "PDF第17页，待裁切单品高清图"
  }),
  product({
    id: 20,
    categoryId: 3,
    brand: "霍尼韦尔 Honeywell",
    sku: "R-01526",
    nameZh: "Impact 电子耳罩",
    nameEn: "Impact Electronic Earmuff",
    summaryZh: "Impact 系列电子耳罩具备主动脉冲噪音降噪功能，同时能放大人声，便于交流。",
    summaryEn: "Electronic earmuff with impulse noise reduction and voice amplification.",
    subcategoryZh: "电子耳罩",
    subcategoryEn: "Electronic earmuff",
    specs: "SNR：25dB\nNRR：22dB\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第17页",
    imageSourceUrl: "PDF第17页，待裁切单品高清图"
  }),
  product({
    id: 21,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "100005",
    nameZh: "SVP OTG 防雾款亚洲款一镜两用安全防护眼镜",
    nameEn: "SVP OTG Anti-Fog Safety Glasses",
    summaryZh: "可容纳多数生活近视镜，超宽容镜空间；镜腿 6 档角度调节、3 档长度调节。",
    summaryEn: "Over-the-glass safety eyewear with wide fit and adjustable temples.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜架及镜腿：黑色\n镜片：透明\n防刮擦：是\n防雾：加强\n使用环境：室内\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第21页",
    imageSourceUrl: "PDF第21页，待裁切单品高清图",
    imageUrl: "/product-images/featured/honeywell-svp-otg-100005.jpg",
    images: [
      "/product-images/featured/honeywell-svp-otg-100005.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 22,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "S99100CN",
    nameZh: "S99 安全防护眼镜透明款",
    nameEn: "S99 Clear Safety Glasses",
    summaryZh: "重量仅 22g 的超轻款聚碳酸酯安全眼镜，防雾镜片避免佩戴口罩或面罩时镜片起雾。",
    summaryEn: "Ultra-light polycarbonate safety eyewear with anti-fog lens.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜片：透明\n防刮擦：是\n防雾：是\n使用环境：室内\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第21页",
    imageSourceUrl: "PDF第21页，待裁切单品高清图",
    imageUrl: "/product-images/featured/honeywell-s99-s99100cn.jpg",
    images: [
      "/product-images/featured/honeywell-s99-s99100cn.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 23,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "100100",
    nameZh: "S200A 亚洲款防冲击眼镜透明款",
    nameEn: "S200A Asian Fit Clear Impact Safety Glasses",
    summaryZh: "专为亚洲人设计，柔软鼻垫和镜腿提供舒适保护，一体式全景镜片设计提供宽阔视野。",
    summaryEn: "Asian-fit impact safety eyewear with soft nose pad, temples, and panoramic lens.",
    subcategoryZh: "防冲击眼镜",
    subcategoryEn: "Impact safety glasses",
    specs: "镜架及镜腿：蓝色\n镜片：透明\n防刮擦：是\n防雾：是\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第22页",
    imageSourceUrl: "PDF第22页，待裁切单品高清图"
  }),
  product({
    id: 24,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "200500",
    nameZh: "LG200A 防护眼罩防雾款",
    nameEn: "LG200A Anti-Fog Safety Goggles",
    summaryZh: "通风孔可关闭，开启时为间接通风；超大防护面积镜片，可选装光学 RX 镜架。",
    summaryEn: "Safety goggles with closable indirect vents and optional RX insert frame.",
    subcategoryZh: "防冲击眼罩",
    subcategoryEn: "Safety goggles",
    specs: "产品描述：透明镜身/布质头带/镜片防雾\n镜片：透明 PC 镜片\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第30页",
    imageSourceUrl: "PDF第30页，待裁切单品高清图",
    imageUrl: "/product-images/featured/honeywell-lg200a-200500.jpg",
    images: [
      "/product-images/featured/honeywell-lg200a-200500.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 25,
    categoryId: 2,
    brand: "霍尼韦尔 Honeywell",
    sku: "1017750pro",
    nameZh: "DuraMaxx 护目镜布质头带款",
    nameEn: "DuraMaxx Goggles with Fabric Headband",
    summaryZh: "镜片可更换，可增配 RX 矫视支架，能匹配霍尼韦尔半面罩；符合 ANSI Z87.1 防液体泼溅 D3 级别。",
    summaryEn: "Replaceable-lens safety goggles compatible with RX insert and Honeywell half masks.",
    subcategoryZh: "防冲击眼罩",
    subcategoryEn: "Safety goggles",
    specs: "镜架及头带：蓝灰色本体，织物头带\n防雾：Hydroshield 超强\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第31页",
    imageSourceUrl: "PDF第31页，待裁切单品高清图",
    imageUrl: "/product-images/featured/honeywell-duramaxx-1017750pro.jpg",
    images: [
      "/product-images/featured/honeywell-duramaxx-1017750pro.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 26,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "ACH2W80100ML",
    nameZh: "Aircore H2 全身式安全带 M/L",
    nameEn: "Aircore H2 Full Body Harness M/L",
    summaryZh: "标准配置重量仅 3.16kg，比同类产品轻 17%；全铝合金挂点及搭扣。",
    summaryEn: "Lightweight full body harness with aluminum alloy attachment points and buckles.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "尺码：M/L\n符合标准：EN361:2002、EN358:1999、EN1497:2007、GB6095、LA认证\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图",
    imageUrl: "/product-images/featured/honeywell-aircore-h2-ach2w80100ml.jpg",
    images: [
      "/product-images/featured/honeywell-aircore-h2-ach2w80100ml.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 27,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1002849A",
    nameZh: "DuraFlex 双挂点全身式安全带",
    nameEn: "DuraFlex Two-Point Full Body Harness",
    summaryZh: "弹性织带带来更好的舒适性和耐用性，搭扣式胸带扣和腿带扣，胸前织带环。",
    summaryEn: "Two-point full body harness with elastic webbing and front web loop.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：双挂点全身式安全带\n符合标准：GB6095\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图"
  }),
  product({
    id: 28,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1002853A",
    nameZh: "DuraFlex 双挂点全身式安全带金属环款",
    nameEn: "DuraFlex Two-Point Full Body Harness with Metal Front Ring",
    summaryZh: "弹性织带，带背部 D 型环和胸前部金属环，符合 GB6095。",
    summaryEn: "DuraFlex harness with dorsal D-ring and metal front ring.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：双挂点全身式安全带\n符合标准：GB6095\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第112页",
    imageSourceUrl: "PDF第112页，待裁切单品高清图"
  }),
  product({
    id: 29,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1011890A",
    nameZh: "Titan 单挂点全身式安全带",
    nameEn: "Titan Single-Point Full Body Harness",
    summaryZh: "全身式可调节设计，一个规格适合多种身形；可滑动背部 D 型环，耐用聚酯织带。",
    summaryEn: "Adjustable single-point full body harness with sliding dorsal D-ring.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：Titan 单挂点全身式安全带\n符合标准：GB6095\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第114页",
    imageSourceUrl: "PDF第114页，待裁切单品高清图"
  }),
  product({
    id: 30,
    categoryId: 5,
    brand: "霍尼韦尔 Honeywell",
    sku: "1011891A",
    nameZh: "Titan 双挂点全身式安全带",
    nameEn: "Titan Two-Point Full Body Harness",
    summaryZh: "全身式可调节设计，带背部 D 型环和胸前部双 D 环。",
    summaryEn: "Adjustable two-point full body harness with dorsal D-ring and front dual D-rings.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "产品描述：Titan 双挂点全身式安全带\n符合标准：GB6095\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE综合样本最新，第114页",
    imageSourceUrl: "PDF第114页，待裁切单品高清图"
  }),
  product({
    id: 31,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120784",
    nameZh: "Advantage 200LS 半面罩呼吸器小号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Small",
    summaryZh: "热塑材料小号半面罩，配套使用 Advantage 系列滤片；符合 GB2890 和 NIOSH 标准。",
    summaryEn: "Thermoplastic half-mask respirator for Advantage filters, small size.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，小号\n标准：GB2890、NIOSH\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 32,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120785",
    nameZh: "Advantage 200LS 半面罩呼吸器中号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Medium",
    summaryZh: "热塑材料中号半面罩，采用 MultiFlex 设计，佩戴时接触面压力均匀。",
    summaryEn: "Thermoplastic half-mask respirator with MultiFlex design, medium size.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，中号\n标准：GB2890、NIOSH\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 33,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10120786",
    nameZh: "Advantage 200LS 半面罩呼吸器大号",
    nameEn: "Advantage 200LS Half-Mask Respirator, Large",
    summaryZh: "热塑材料大号半面罩，轻巧柔软，低轮廓设计便于与眼镜、眼罩或耳罩搭配。",
    summaryEn: "Thermoplastic half-mask respirator, large size, with low-profile design.",
    subcategoryZh: "半面罩呼吸器",
    subcategoryEn: "Half-mask respirator",
    specs: "产品描述：热塑材料，大号\n标准：GB2890、NIOSH\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图"
  }),
  product({
    id: 34,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10147997",
    nameZh: "Advantage 3100 全面罩呼吸器中号",
    nameEn: "Advantage 3100 Full-Facepiece Respirator, Medium",
    summaryZh: "热塑材料中号全面罩，内置口鼻罩，聚碳酸酯透镜视野宽阔，面屏带防刮镀层。",
    summaryEn: "Full-facepiece respirator with thermoplastic body and polycarbonate lens, medium size.",
    subcategoryZh: "全面罩呼吸器",
    subcategoryEn: "Full-facepiece respirator",
    specs: "产品描述：热塑材料，中号\n标准：GB2890、NIOSH\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第7页",
    imageSourceUrl: "PDF第7页，待裁切单品高清图",
    imageUrl: "/product-images/featured/msa-advantage-3100-10147997.jpg",
    images: [
      "/product-images/featured/msa-advantage-3100-10147997.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 35,
    categoryId: 1,
    brand: "MSA 梅思安",
    sku: "10081114",
    nameZh: "OptimAir TL 动力送风过滤式呼吸器主机",
    nameEn: "OptimAir TL PAPR Blower Unit",
    summaryZh: "NIOSH 认证动力送风过滤式呼吸器主机，可配套送风头罩和全面罩，帮助防护颗粒物、有毒气体和有机蒸气。",
    summaryEn: "PAPR blower unit for use with loose-fitting hoods and tight-fitting full facepieces.",
    subcategoryZh: "动力送风过滤式呼吸器",
    subcategoryEn: "PAPR",
    specs: "产品编号：10081114\n符合：GB30864\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第10页",
    imageSourceUrl: "PDF第10页，待裁切单品高清图"
  }),
  product({
    id: 36,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10240493",
    nameZh: "M8-1800 正压式消防空气呼吸器 6.8L 有表瓶阀网状头带",
    nameEn: "M8-1800 SCBA 6.8L with Gauge Valve and Mesh Head Harness",
    summaryZh: "M8-1800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，有表瓶阀，G1 全面罩 Fix-PTC 中号网状头带配置。",
    summaryEn: "M8-1800 SCBA configuration with 6.8L cylinder, gauge valve, and G1 medium facepiece.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n面罩：G1 全面罩 Fix-PTC，中号，网状头带\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图",
    imageUrl: "/product-images/featured/msa-m8-1800-10240493.jpg",
    images: [
      "/product-images/featured/msa-m8-1800-10240493.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 37,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10240494",
    nameZh: "M8-1800 正压式消防空气呼吸器 6.8L 无表瓶阀网状头带",
    nameEn: "M8-1800 SCBA 6.8L without Gauge Valve, Mesh Head Harness",
    summaryZh: "M8-1800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，无表瓶阀，G1 全面罩 Fix-PTC 中号网状头带配置。",
    summaryEn: "M8-1800 SCBA configuration with 6.8L cylinder without gauge valve and G1 medium facepiece.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n面罩：G1 全面罩 Fix-PTC，中号，网状头带\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图"
  }),
  product({
    id: 38,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10241461",
    nameZh: "M8-2800 正压式消防空气呼吸器 6.8L 有表限流瓶阀",
    nameEn: "M8-2800 SCBA 6.8L with Gauge Flow-Limiting Valve",
    summaryZh: "M8-2800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，有表限流瓶阀，PR18C 减压器配置。",
    summaryEn: "M8-2800 SCBA with 6.8L cylinder, gauge flow-limiting valve, and PR18C reducer.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n减压器：PR18C\n面罩：G1 面罩 Fix-PTC，中号，网状头带\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图",
    imageUrl: "/product-images/featured/msa-m8-2800-10241461.jpg",
    images: [
      "/product-images/featured/msa-m8-2800-10241461.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 39,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10241462",
    nameZh: "M8-2800 正压式消防空气呼吸器 6.8L 无表限流瓶阀",
    nameEn: "M8-2800 SCBA 6.8L without Gauge Flow-Limiting Valve",
    summaryZh: "M8-2800 正压式消防空气呼吸器，6.8L 30MPa 非荧光气瓶，无表限流瓶阀，PR18C 减压器配置。",
    summaryEn: "M8-2800 SCBA with 6.8L cylinder without gauge flow-limiting valve and PR18C reducer.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "气瓶：北京天海 6.8L，30MPa\n减压器：PR18C\n面罩：G1 面罩 Fix-PTC，中号，网状头带\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第14页",
    imageSourceUrl: "PDF第14页，待裁切单品高清图"
  }),
  product({
    id: 40,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "10242202",
    nameZh: "G1 全面罩 Fix-PTC 接口中号网状头带",
    nameEn: "G1 Full Facepiece Fix-PTC, Medium, Mesh Head Harness",
    summaryZh: "G1 全面罩销售单元，Fix-PTC 接口，中号，网状头带，可作为 M8 系列空呼配置面罩。",
    summaryEn: "G1 full facepiece sales unit with Fix-PTC interface, medium size, mesh head harness.",
    subcategoryZh: "消防空气呼吸器面罩",
    subcategoryEn: "SCBA facepiece",
    specs: "接口：Fix-PTC\n尺码：中号\n头带：网状头带\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第13页",
    imageSourceUrl: "PDF第13页，待裁切单品高清图"
  }),
  product({
    id: 41,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "ULTIMA X5000",
    nameZh: "ULTIMA X5000 气体探测器",
    nameEn: "ULTIMA X5000 Universal Gas Detector",
    summaryZh: "统一平台气体探测器，集成电化学、催化燃烧、红外吸收等检测技术，支持双探头灵活组合。",
    summaryEn: "Universal gas detector platform integrating electrochemical, catalytic bead, and infrared technologies.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "通讯：HART、Modbus RS485、无线 HART\n特点：OLED 显示、触摸屏、TruCal 智能传感技术\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第79页",
    imageSourceUrl: "PDF第79页，待裁切单品高清图",
    imageUrl: "/product-images/featured/msa-ultima-x5000.jpg",
    images: [
      "/product-images/featured/msa-ultima-x5000.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 42,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "PrimaX P/I",
    nameZh: "PrimaX P/I 气体探测器",
    nameEn: "PrimaX P/I Gas Detector",
    summaryZh: "PrimaX P 隔爆型可检测可燃性气体、有毒气体和氧气；PrimaX I 本安型采用电化学原理检测毒气和氧气。",
    summaryEn: "PrimaX P/I gas detector for combustible, toxic gas, and oxygen monitoring.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "认证：CCC、CPA、Ex、ATEX/IECEx、SIL2、EAC\n输出：4-20mA，HART 和继电器可选\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 43,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "PrimaX IR",
    nameZh: "PrimaX IR 系列红外可燃气体探测器",
    nameEn: "PrimaX IR Combustible Gas Detector",
    summaryZh: "采用高性能红外传感器，双重红外光源冗余设计，T90 小于 5 秒。",
    summaryEn: "Infrared combustible gas detector with redundant IR sources and T90 under 5 seconds.",
    subcategoryZh: "红外可燃气体探测器",
    subcategoryEn: "Infrared combustible gas detector",
    specs: "工作温度：-40℃至+70℃\n认证：CCC、CPA、SIL2、Ex d IIC T4\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 44,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "DF-8500SIL",
    nameZh: "DF-8500SIL 气体探测器",
    nameEn: "DF-8500SIL Gas Detector",
    summaryZh: "采用催化燃烧以及电化学原理，可检测可燃性气体和有毒有害气体。",
    summaryEn: "Gas detector using catalytic bead and electrochemical technologies.",
    subcategoryZh: "固定式气体探测器",
    subcategoryEn: "Fixed gas detector",
    specs: "防护等级：IP66/IP67\n认证：CCC、CPA、Ex、CCS、SIL2\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第80页",
    imageSourceUrl: "PDF第80页，待裁切单品高清图"
  }),
  product({
    id: 45,
    categoryId: 6,
    brand: "MSA 梅思安",
    sku: "FlameGard 5 MSIR",
    nameZh: "FlameGard 5 MSIR 四频红外火焰探测器",
    nameEn: "FlameGard 5 MSIR Multi-Spectrum InfraRed Flame Detector",
    summaryZh: "四频红外火焰探测器，采用 ANN 智能神经元网络技术，有效区分真实火焰与干扰源。",
    summaryEn: "Multi-spectrum infrared flame detector with ANN technology.",
    subcategoryZh: "火焰探测器",
    subcategoryEn: "Flame detector",
    specs: "典型响应时间：5秒\n最远检测距离：70米\n认证：ATEX/IECEx、CSA、FM、UL、CCC、SIL3\n状态：已上架，图片和资料可继续优化",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA_梅思安_综合样本_Rev2024_CN，第81页",
    imageSourceUrl: "PDF第81页，待裁切单品高清图",
    imageUrl: "/product-images/featured/msa-flamegard-5-msir.jpg",
    images: [
      "/product-images/featured/msa-flamegard-5-msir.jpg"
    ],
    status: "PUBLISHED"
  }),
  product({
    id: 46,
    categoryId: 1,
    brand: "3M",
    sku: "9501V+ / 9542V",
    nameZh: "3M 9501V+ / 9542V KN95 防颗粒物口罩",
    nameEn: "3M 9501V+ / 9542V KN95 Particulate Respirators",
    summaryZh: "3M KN95 防颗粒物口罩系列，适用于工业粉尘颗粒物防护，配置冷流呼气阀、可调鼻夹和静电滤棉。",
    summaryEn: "3M KN95 particulate respirator series with cool-flow valve, adjustable nose clip, and electrostatic filter media.",
    subcategoryZh: "随弃式防颗粒物口罩",
    subcategoryEn: "Disposable particulate respirator",
    specs: "型号：9501V+、9542V\n认证：中国 KN95\n特点：冷流呼气阀、静电滤棉、亚洲人脸型设计、下巴处无焊缝设计",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，KN95 防颗粒物口罩页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/01-kn95-9501v-9542v.png",
    imageUrl: "/product-images/catalog-pages/3m/01-kn95-9501v-9542v.png"
  }),
  product({
    id: 47,
    categoryId: 1,
    brand: "3M",
    sku: "HF-801SD / HF-802SD",
    nameZh: "3M HF-800 系列呼吸防护半面罩",
    nameEn: "3M HF-800 Series Half-Mask Respirators",
    summaryZh: "3M HF-800 系列半面罩，双滤盒设计，适用于颗粒物及多种气体和蒸气防护。",
    summaryEn: "3M HF-800 half-mask respirator series for particulate, gas, and vapor protection with dual filter cartridges.",
    subcategoryZh: "可重复使用半面罩",
    subcategoryEn: "Reusable half-mask respirator",
    specs: "型号：HF-801SD 小号、HF-802SD 中号\n特点：传声膜、气密性检查按钮、硅胶密封圈、易调节头带、呼吸阻力低",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，HF-800 系列页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/02-hf800-half-mask.png",
    imageUrl: "/product-images/catalog-pages/3m/02-hf800-half-mask.png"
  }),
  product({
    id: 48,
    categoryId: 1,
    brand: "3M",
    sku: "FF-802",
    nameZh: "3M FF-800 硅胶系列呼吸防护全面罩",
    nameEn: "3M FF-800 Series Full-Facepiece Respirator",
    summaryZh: "3M FF-800 系列全面罩，双滤盒设计，适用于颗粒物及多种气体和蒸气防护。",
    summaryEn: "3M FF-800 full-facepiece respirator with dual-filter connection for particulate, gas, and vapor protection.",
    subcategoryZh: "可重复使用全面罩",
    subcategoryEn: "Reusable full-facepiece respirator",
    specs: "型号：FF-802 中号\n特点：大视窗、传声膜、气密性检查按钮、舒适头架、呼气阀",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，FF-800 系列页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/03-ff800-full-facepiece.png",
    imageUrl: "/product-images/catalog-pages/3m/03-ff800-full-facepiece.png"
  }),
  product({
    id: 49,
    categoryId: 1,
    brand: "3M",
    sku: "D8001CN / D8003CN / D8006CN / D80926CN",
    nameZh: "3M HF-800 / FF-800 系列滤毒盒及滤棉",
    nameEn: "3M HF-800 / FF-800 Filter Cartridges and Filters",
    summaryZh: "适配 3M HF-800 与 FF-800 系列面罩的滤毒盒、滤棉及滤盖产品。",
    summaryEn: "Filter cartridges, filters, and retainers for 3M HF-800 and FF-800 respirators.",
    subcategoryZh: "呼吸防护滤盒滤棉",
    subcategoryEn: "Respirator cartridges and filters",
    specs: "型号：D8001CN、D8003CN、D8006CN、D80926CN、D3076HF、D3091CN、D3097CN、D9093CN、D7N11CN、D7P71CN、D701CN",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，HF-800/FF-800 滤盒滤棉页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/04-hf-ff800-filters.png",
    imageUrl: "/product-images/catalog-pages/3m/04-hf-ff800-filters.png"
  }),
  product({
    id: 50,
    categoryId: 1,
    brand: "3M",
    sku: "FF-402 / FF-403",
    nameZh: "3M FF-400 硅胶系列呼吸防护全面罩",
    nameEn: "3M FF-400 Series Silicone Full-Facepiece Respirators",
    summaryZh: "3M FF-400 硅胶全面罩，适合高强度工业呼吸防护场景。",
    summaryEn: "3M FF-400 silicone full-facepiece respirators for demanding industrial respiratory protection.",
    subcategoryZh: "可重复使用全面罩",
    subcategoryEn: "Reusable full-facepiece respirator",
    specs: "型号：FF-402 中号、FF-403 大号\n特点：Scotchgard 防护涂层、大视窗、硅胶密封圈、传声膜、冷流呼气阀",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，FF-400 系列页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/05-ff400-full-facepiece.png",
    imageUrl: "/product-images/catalog-pages/3m/05-ff400-full-facepiece.png"
  }),
  product({
    id: 51,
    categoryId: 1,
    brand: "3M",
    sku: "6700 / 6800 / 6900",
    nameZh: "3M 6000 系列呼吸防护全面罩",
    nameEn: "3M 6000 Series Full-Facepiece Respirators",
    summaryZh: "3M 6000 系列全面罩，可配多种滤毒盒和滤棉，适用于多种气体、蒸气和颗粒物防护。",
    summaryEn: "3M 6000 series full-facepiece respirators compatible with multiple cartridges and filters.",
    subcategoryZh: "可重复使用全面罩",
    subcategoryEn: "Reusable full-facepiece respirator",
    specs: "型号：6700 小号、6800 中号、6900 大号\n特点：大视窗、轻质平衡设计、冷流呼气阀、中央适配器、卡口式装配",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，6000 全面罩页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/06-6000-full-facepiece.png",
    imageUrl: "/product-images/catalog-pages/3m/06-6000-full-facepiece.png"
  }),
  product({
    id: 52,
    categoryId: 1,
    brand: "3M",
    sku: "7501 / 7502",
    nameZh: "3M 7500 硅胶系列呼吸防护半面罩",
    nameEn: "3M 7500 Series Silicone Half-Mask Respirators",
    summaryZh: "3M 7500 系列硅胶半面罩，适合长时间佩戴和多种工业防护应用。",
    summaryEn: "3M 7500 silicone half-mask respirators for extended wear and broad industrial applications.",
    subcategoryZh: "可重复使用半面罩",
    subcategoryEn: "Reusable half-mask respirator",
    specs: "型号：7501 小号、7502 中号\n特点：硅胶材质、可调头架、冷流呼气阀、向下呼气口、卡口式装配",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，7500 系列页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/07-7500-half-mask.png",
    imageUrl: "/product-images/catalog-pages/3m/07-7500-half-mask.png"
  }),
  product({
    id: 53,
    categoryId: 1,
    brand: "3M",
    sku: "6100 / 6200",
    nameZh: "3M 6000 系列呼吸防护半面罩",
    nameEn: "3M 6000 Series Half-Mask Respirators",
    summaryZh: "3M 6000 系列半面罩，经典经济型双滤盒呼吸防护产品。",
    summaryEn: "3M 6000 series economical reusable half-mask respirators with dual-filter connection.",
    subcategoryZh: "可重复使用半面罩",
    subcategoryEn: "Reusable half-mask respirator",
    specs: "型号：6100 小号、6200 中号\n特点：双罐式面罩、低轮廓设计、高级橡胶材质、卡口式装配",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，6000 半面罩页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/08-6000-half-mask.png",
    imageUrl: "/product-images/catalog-pages/3m/08-6000-half-mask.png"
  }),
  product({
    id: 54,
    categoryId: 1,
    brand: "3M",
    sku: "6001CN-6007CN / 60926 / 60928",
    nameZh: "3M 6000 / 7500 / FF-400 系列滤毒盒及滤棉",
    nameEn: "3M 6000 / 7500 / FF-400 Cartridge and Filter Family",
    summaryZh: "适配 3M 6000、7500、FF-400 系列面罩的滤毒盒、滤棉和滤盖产品。",
    summaryEn: "Cartridges, filters, and retainers for 3M 6000, 7500, and FF-400 respirator systems.",
    subcategoryZh: "呼吸防护滤盒滤棉",
    subcategoryEn: "Respirator cartridges and filters",
    specs: "型号：6001CN、6002CN、6003CN、6004CN、6005CN、6006CN、6007CN、60926、60928、5N11CN、501",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，6000/7500/FF-400 滤盒滤棉页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/10-6000-7500-ff400-cartridges.png",
    imageUrl: "/product-images/catalog-pages/3m/10-6000-7500-ff400-cartridges.png"
  }),
  product({
    id: 55,
    categoryId: 1,
    brand: "3M",
    sku: "3100 / 3200",
    nameZh: "3M 3000 系列呼吸防护半面罩及配件",
    nameEn: "3M 3000 Series Half-Mask Respirators and Accessories",
    summaryZh: "3M 3000 系列半面罩及配套滤棉、滤毒盒、滤盖和转换配件。",
    summaryEn: "3M 3000 series half-mask respirators with filters, cartridges, retainers, and adapters.",
    subcategoryZh: "可重复使用半面罩",
    subcategoryEn: "Reusable half-mask respirator",
    specs: "型号：3100、3200、3700、3701CN、3744CN、3303CN、3301CN、3N11CN、395CN",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，3000 系列页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/12-3000-half-mask-and-filters.png",
    imageUrl: "/product-images/catalog-pages/3m/12-3000-half-mask-and-filters.png"
  }),
  product({
    id: 56,
    categoryId: 7,
    brand: "3M",
    sku: "SCOTT iPak20",
    nameZh: "3M SCOTT iPak20 正压式消防空气呼吸器",
    nameEn: "3M SCOTT iPak20 Positive Pressure Fire SCBA",
    summaryZh: "3M SCOTT iPak20 正压式消防空气呼吸器，适用于消防和工业高风险呼吸防护场景。",
    summaryEn: "3M SCOTT iPak20 positive pressure fire SCBA for firefighting and high-risk industrial respiratory protection.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "标准：XF 124-2013\n特点：新概念背板、TANCO 减压阀、PANO 全面罩、智能化空呼辅助模块、可选救援附件",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，SCOTT iPak20 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/20-scott-ipak20-scba.png",
    imageUrl: "/product-images/catalog-pages/3m/20-scott-ipak20-scba.png"
  }),
  product({
    id: 57,
    categoryId: 1,
    brand: "3M",
    sku: "SCOTT CG-8",
    nameZh: "3M SCOTT CG-8 长管呼吸器",
    nameEn: "3M SCOTT CG-8 Supplied-Air Respirator",
    summaryZh: "3M SCOTT CG-8 长管呼吸器，支持移动气源、供气管路和应急供气配置。",
    summaryEn: "3M SCOTT CG-8 supplied-air respirator system with mobile air source and airline options.",
    subcategoryZh: "供气式呼吸器",
    subcategoryEn: "Supplied-air respirator",
    specs: "配置：移动气源、RAS 基本供气装置、AV3000 面罩、中压供气管、Y 型三通、应急供气装置",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，SCOTT CG-8 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/21-scott-cg8-supplied-air-respirator.png",
    imageUrl: "/product-images/catalog-pages/3m/21-scott-cg8-supplied-air-respirator.png"
  }),
  product({
    id: 58,
    categoryId: 3,
    brand: "3M",
    sku: "PELTOR X / OPTIME",
    nameZh: "3M PELTOR X 与 OPTIME 系列耳罩",
    nameEn: "3M PELTOR X and OPTIME Earmuff Series",
    summaryZh: "3M PELTOR X、OPTIME 95、OPTIME 101 系列耳罩，覆盖头带式、颈带式和安全帽连接式配置。",
    summaryEn: "3M PELTOR X, OPTIME 95, and OPTIME 101 earmuff series in headband, neckband, and helmet-mounted versions.",
    subcategoryZh: "工业降噪耳罩",
    subcategoryEn: "Industrial earmuff",
    specs: "型号：X4A、X5A、X4P3、X5P3、H6A、H6B、H6F、H6P3E、H7A、H7B、H7P3E\n参数：不同型号 NRR/SNR 不同，以目录为准",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，PELTOR 耳罩页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/13-peltor-earmuffs.png",
    imageUrl: "/product-images/catalog-pages/3m/13-peltor-earmuffs.png"
  }),
  product({
    id: 59,
    categoryId: 2,
    brand: "3M",
    sku: "SecureFit 3700",
    nameZh: "3M SecureFit 3700 系列中国款 OTG 安全眼镜",
    nameEn: "3M SecureFit 3700 OTG Safety Glasses",
    summaryZh: "3M SecureFit 3700 系列 OTG 安全眼镜，适合佩戴近视眼镜人员使用。",
    summaryEn: "3M SecureFit 3700 OTG safety glasses designed for use over prescription eyewear.",
    subcategoryZh: "防护眼镜",
    subcategoryEn: "Safety glasses",
    specs: "型号：SF3701ASGAF-BLU、SF3702ASGAF-BLU、SF3707ASGAF-BLU、SF3703ASGAF-GRN、SF3701XASGAF-RED\n特点：压力扩散镜腿技术、聚碳酸酯镜片、Scotchgard 防雾涂层",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，SecureFit 3700 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/14-securefit-3700-otg.png",
    imageUrl: "/product-images/catalog-pages/3m/14-securefit-3700-otg.png"
  }),
  product({
    id: 60,
    categoryId: 5,
    brand: "3M",
    sku: "ExoFit Light",
    nameZh: "3M DBI-SALA ExoFit Light 全身式系带",
    nameEn: "3M DBI-SALA ExoFit Light Full Body Harness",
    summaryZh: "3M DBI-SALA ExoFit Light 全身式系带，提供多尺码、多颜色和不同挂点配置。",
    summaryEn: "3M DBI-SALA ExoFit Light full body harness series with multiple sizes, colors, and D-ring configurations.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "型号：1114189、1114190、1114191、1114183、1114184、1114185、1103587、1103588、1103589、1103590、1103591、1103592",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，ExoFit Light 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/15-exofit-light-harness.png",
    imageUrl: "/product-images/catalog-pages/3m/15-exofit-light-harness.png"
  }),
  product({
    id: 61,
    categoryId: 5,
    brand: "3M",
    sku: "Protecta P200",
    nameZh: "3M Protecta P200 全身式系带",
    nameEn: "3M Protecta P200 Full Body Harness",
    summaryZh: "3M Protecta P200 全身式系带，覆盖背心式、安全钩、胸前 D 型环和腰带衬垫等配置。",
    summaryEn: "3M Protecta P200 full body harness series with vest-style, D-ring, and waist pad configurations.",
    subcategoryZh: "全身式安全带",
    subcategoryEn: "Full body harness",
    specs: "型号：1161729、1161730、1161731、1161732、1161733、1161734、1161735、1161736",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，Protecta P200 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/16-protecta-p200-harness.png",
    imageUrl: "/product-images/catalog-pages/3m/16-protecta-p200-harness.png"
  }),
  product({
    id: 62,
    categoryId: 5,
    brand: "3M",
    sku: "Sealed-Blok",
    nameZh: "3M DBI-SALA Sealed-Blok 密封式速差自控器",
    nameEn: "3M DBI-SALA Sealed-Blok Self-Retracting Lifeline",
    summaryZh: "3M DBI-SALA Sealed-Blok 密封式速差自控器，适用于油脂、污垢和湿气影响较大的高处作业场景。",
    summaryEn: "3M DBI-SALA Sealed-Blok self-retracting lifeline for harsh fall protection environments.",
    subcategoryZh: "速差自控器",
    subcategoryEn: "Self-retracting lifeline",
    specs: "长度：9m、15m；可选 3-way 回收配置\n特点：密封设计、IP68、防腐蚀材料、自锁旋转钩",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，Sealed-Blok 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/18-sealed-blok-srl.png",
    imageUrl: "/product-images/catalog-pages/3m/18-sealed-blok-srl.png"
  }),
  product({
    id: 63,
    categoryId: 5,
    brand: "3M",
    sku: "Nano-Lok Light",
    nameZh: "3M DBI-SALA Nano-Lok Light 小型速差自控器",
    nameEn: "3M DBI-SALA Nano-Lok Light Self-Retracting Lifeline",
    summaryZh: "3M DBI-SALA Nano-Lok Light 小型速差自控器，轻量化设计，适合移动作业和高处防坠落应用。",
    summaryEn: "3M DBI-SALA Nano-Lok Light self-retracting lifeline with lightweight design for mobile work at height.",
    subcategoryZh: "速差自控器",
    subcategoryEn: "Self-retracting lifeline",
    specs: "型号：3101765 大钩、3101766 小钩、双钩配置\n标准：GB 24544-2023\n载荷：45-100kg",
    sourceUrl: "https://www.3m.com.cn/3M/zh_CN/company-cn/",
    sourceDocument: "3M 个人安全防护产品目录，Nano-Lok Light 页",
    imageSourceUrl: "docs/product-references/3m-industrial-safety/19-nano-lok-light-srl.png",
    imageUrl: "/product-images/catalog-pages/3m/19-nano-lok-light-srl.png"
  }),
  product({
    id: 64,
    categoryId: 7,
    brand: "霍尼韦尔 Honeywell",
    sku: "T8500",
    nameZh: "霍尼韦尔 T8500 自给式消防及工业用空气呼吸器",
    nameEn: "Honeywell T8500 SCBA for Firefighting and Industrial Use",
    summaryZh: "霍尼韦尔 T8500 自给式空气呼吸器，适用于消防和工业高风险呼吸防护场景。",
    summaryEn: "Honeywell T8500 self-contained breathing apparatus for firefighting and industrial respiratory protection.",
    subcategoryZh: "自给开路式压缩空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "特点：新概念背板、PANO 全面罩、TANCO 减压阀、耳边报警哨、隐形管路槽、可选通讯和救援附件",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，T8500 页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/01-t8500-scba.png",
    imageUrl: "/product-images/catalog-pages/honeywell/01-t8500-scba.png"
  }),
  product({
    id: 65,
    categoryId: 7,
    brand: "霍尼韦尔 Honeywell",
    sku: "T8000",
    nameZh: "霍尼韦尔 T8000 自给开路式压缩空气呼吸器",
    nameEn: "Honeywell T8000 Self-Contained Compressed-Air Breathing Apparatus",
    summaryZh: "霍尼韦尔 T8000 空气呼吸器，通过 EN137-2006 自给开路式压缩空气呼吸器标准。",
    summaryEn: "Honeywell T8000 self-contained compressed-air breathing apparatus tested to EN137-2006.",
    subcategoryZh: "自给开路式压缩空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "标准：EN137-2006、GA124-2004、GB/T 16556-2007\n特点：一级减压系统、高压管报警系统、Banjo 供气阀接头",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，T8000 页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/02-t8000-scba.png",
    imageUrl: "/product-images/catalog-pages/honeywell/02-t8000-scba.png"
  }),
  product({
    id: 66,
    categoryId: 7,
    brand: "霍尼韦尔 Honeywell",
    sku: "C900",
    nameZh: "霍尼韦尔 C900 自给开路式压缩空气呼吸器",
    nameEn: "Honeywell C900 Self-Contained Compressed-Air Breathing Apparatus",
    summaryZh: "霍尼韦尔 C900 空气呼吸器，配 PANO 全面罩和可靠减压器配置。",
    summaryEn: "Honeywell C900 SCBA with PANO full facepiece and reducer configurations.",
    subcategoryZh: "自给开路式压缩空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "订货号：SCBA105L、SCBA123L、SCBA124、SCBA126\n配置：6.8L/9L LUXFER 碳瓶，单瓶或双瓶配置",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，C900 页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/03-c900-scba.png",
    imageUrl: "/product-images/catalog-pages/honeywell/03-c900-scba.png"
  }),
  product({
    id: 67,
    categoryId: 4,
    brand: "霍尼韦尔 Honeywell",
    sku: "LA102GCN / LA132GCN / 2094831GCN",
    nameZh: "霍尼韦尔丁腈防化手套系列",
    nameEn: "Honeywell Nitrile Chemical-Resistant Gloves",
    summaryZh: "霍尼韦尔丁腈防化手套系列，适用于化学处理、石化、精细化工等环境。",
    summaryEn: "Honeywell nitrile chemical-resistant glove series for chemical handling and industrial applications.",
    subcategoryZh: "防化手套",
    subcategoryEn: "Chemical-resistant gloves",
    specs: "型号：LA102GCN、LA132GCN、2094831GCN\n材质：丁腈\n尺寸：7-10 或 8-10，以目录为准",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，防化手套页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/04-chemical-protection-gloves.png",
    imageUrl: "/product-images/catalog-pages/honeywell/04-chemical-protection-gloves.png"
  }),
  product({
    id: 68,
    categoryId: 4,
    brand: "霍尼韦尔 Honeywell",
    sku: "2095020 / 2095025 / B131R",
    nameZh: "霍尼韦尔氯丁橡胶与丁基橡胶防化手套",
    nameEn: "Honeywell Chloroprene and Butyl Rubber Chemical Gloves",
    summaryZh: "霍尼韦尔氯丁橡胶与丁基橡胶防化手套，适用于多种化学品防护场景。",
    summaryEn: "Honeywell chloroprene and butyl rubber chemical gloves for chemical protection applications.",
    subcategoryZh: "防化手套",
    subcategoryEn: "Chemical-resistant gloves",
    specs: "型号：2095020、2095025、B131R\n材质：氯丁橡胶、丁基橡胶\n用途：化工、工业清洗、石油化工、水处理等",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，防化手套页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/04-chemical-protection-gloves.png",
    imageUrl: "/product-images/catalog-pages/honeywell/04-chemical-protection-gloves.png"
  }),
  product({
    id: 69,
    categoryId: 8,
    brand: "霍尼韦尔 Honeywell",
    sku: "SHGP21102 / SHGP21112 / SHGP21202 / SHGP21212",
    nameZh: "霍尼韦尔 PU/RUBBER 复合大底安全鞋",
    nameEn: "Honeywell PU/Rubber Composite Sole Safety Shoes",
    summaryZh: "霍尼韦尔 PU/RUBBER 复合大底安全鞋，覆盖低帮和中帮 S1P 配置。",
    summaryEn: "Honeywell PU/rubber composite sole safety shoes in low-cut and mid-cut S1P versions.",
    subcategoryZh: "安全鞋",
    subcategoryEn: "Safety shoes",
    specs: "型号：SHGP21102、SHGP21112、SHGP21202、SHGP21212\n防护：保护足趾、防刺穿、防静电",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，PU/RUBBER 安全鞋页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/05-pu-rubber-safety-shoes.png",
    imageUrl: "/product-images/catalog-pages/honeywell/05-pu-rubber-safety-shoes.png"
  }),
  product({
    id: 70,
    categoryId: 8,
    brand: "霍尼韦尔 Honeywell",
    sku: "ECO / ECO II / RACING",
    nameZh: "霍尼韦尔 ECO、ECO II 与 RACING 系列安全鞋",
    nameEn: "Honeywell ECO, ECO II, and RACING Safety Shoes",
    summaryZh: "霍尼韦尔 ECO、ECO II 与 RACING 系列工业安全鞋，适合多种工业作业环境。",
    summaryEn: "Honeywell ECO, ECO II, and RACING industrial safety shoe series for varied work environments.",
    subcategoryZh: "安全鞋",
    subcategoryEn: "Safety shoes",
    specs: "型号：BC0919701、BC0919703、BC0919702、BC0919702E、BC09192701、BC09192703、BC6242121、BC6242122\n标准：中国国标 GB21148-2020",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，ECO/RACING 安全鞋页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/06-eco-racing-safety-shoes.png",
    imageUrl: "/product-images/catalog-pages/honeywell/06-eco-racing-safety-shoes.png"
  }),
  product({
    id: 71,
    categoryId: 8,
    brand: "霍尼韦尔 Honeywell",
    sku: "TRIPPER / NEW TRIPPER",
    nameZh: "霍尼韦尔 TRIPPER 与 NEW TRIPPER 系列安全鞋",
    nameEn: "Honeywell TRIPPER and NEW TRIPPER Safety Shoes",
    summaryZh: "霍尼韦尔 TRIPPER 与 NEW TRIPPER 系列轻便安全鞋，适合日常工业安全防护。",
    summaryEn: "Honeywell TRIPPER and NEW TRIPPER lightweight safety shoes for industrial protection.",
    subcategoryZh: "安全鞋",
    subcategoryEn: "Safety shoes",
    specs: "型号：SP2010500 至 SP2010513E，SHTP00501 至 SHTP00503\n标准：中国国标 GB21148-2020",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，TRIPPER 安全鞋页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/07-tripper-safety-shoes.png",
    imageUrl: "/product-images/catalog-pages/honeywell/07-tripper-safety-shoes.png"
  }),
  product({
    id: 72,
    categoryId: 8,
    brand: "霍尼韦尔 Honeywell",
    sku: "Easy / Bold / NMX",
    nameZh: "霍尼韦尔 PVC 安全靴与 NMX 重型橡胶工矿靴",
    nameEn: "Honeywell PVC Safety Boots and NMX Heavy-Duty Rubber Mining Boots",
    summaryZh: "霍尼韦尔 PVC 安全靴与 NMX 重型橡胶工矿靴，适用于化工、食品、污水处理、采矿等场景。",
    summaryEn: "Honeywell PVC safety boots and NMX heavy-duty rubber mining boots for chemical, food, wastewater, and mining applications.",
    subcategoryZh: "安全靴",
    subcategoryEn: "Safety boots",
    specs: "型号：75707、75708、75808、NMX6801、NMX6802、NMX880P、NMX960P\n标准：中国国标 GB21148-2020",
    sourceUrl: "https://www.honeywell.com.cn/products-services/building-technologies/fire",
    sourceDocument: "霍尼韦尔 PPE 综合样本，PVC/NMX 安全靴页",
    imageSourceUrl: "docs/product-references/honeywell-industrial-safety/08-pvc-nmx-safety-boots.png",
    imageUrl: "/product-images/catalog-pages/honeywell/08-pvc-nmx-safety-boots.png"
  }),
  product({
    id: 73,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "F2XT / F3",
    nameZh: "MSA F2XT 救援头盔与 F3 消防头盔",
    nameEn: "MSA F2XT Rescue Helmet and F3 Fire Helmet",
    summaryZh: "MSA F2XT 救援头盔与 F3 消防头盔，适用于消防救援和高风险应急场景。",
    summaryEn: "MSA F2XT rescue helmet and F3 fire helmet for rescue and firefighting applications.",
    subcategoryZh: "消防救援头盔",
    subcategoryEn: "Fire and rescue helmets",
    specs: "型号：F2XT、F3\n标准：EN16471、EN12492、EN16473、NFPA1971-2018、XF 44-2015 等，以目录为准",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，F2XT/F3 头盔页",
    imageSourceUrl: "docs/product-references/msa-safety/01-f2xt-f3-helmets.png",
    imageUrl: "/product-images/catalog-pages/msa/01-f2xt-f3-helmets.png"
  }),
  product({
    id: 74,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "F1XF / F2XR",
    nameZh: "MSA F1XF 消防头盔与 F2XR 多用途救援头盔",
    nameEn: "MSA F1XF Fire Helmet and F2XR Multi-Purpose Rescue Helmet",
    summaryZh: "MSA F1XF 消防头盔与 F2XR 多用途救援头盔，覆盖消防灭火和多场景救援应用。",
    summaryEn: "MSA F1XF fire helmet and F2XR multi-purpose rescue helmet for firefighting and rescue scenarios.",
    subcategoryZh: "消防救援头盔",
    subcategoryEn: "Fire and rescue helmets",
    specs: "型号：F1XF、F2XR\n特点：面罩、护目镜、听力防护、照明等多种附件配置，标准以目录为准",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，F1XF/F2XR 头盔页",
    imageSourceUrl: "docs/product-references/msa-safety/02-f1xf-f2xr-helmets.png",
    imageUrl: "/product-images/catalog-pages/msa/02-f1xf-f2xr-helmets.png"
  }),
  product({
    id: 75,
    categoryId: 8,
    brand: "MSA 梅思安",
    sku: "V-Gard / V-Gard 500",
    nameZh: "MSA V-Gard 标准型与 500 豪华型安全帽",
    nameEn: "MSA V-Gard Standard and V-Gard 500 Hard Hats",
    summaryZh: "MSA V-Gard 标准型安全帽与 V-Gard 500 豪华型安全帽，适用于工业头部防护。",
    summaryEn: "MSA V-Gard Standard and V-Gard 500 hard hats for industrial head protection.",
    subcategoryZh: "工业安全帽",
    subcategoryEn: "Industrial hard hats",
    specs: "型号：V-Gard 标准型、V-Gard 500\n材质：ABS、HDPE 可选\n颜色：白、黄、橙、红、蓝、湖蓝等，以目录为准",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，V-Gard 安全帽页",
    imageSourceUrl: "docs/product-references/msa-safety/03-vgard-hard-hats.png",
    imageUrl: "/product-images/catalog-pages/msa/03-vgard-hard-hats.png"
  }),
  product({
    id: 76,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "MSA 250/300 / 200T/250T/300T / 100TE",
    nameZh: "MSA 高压呼吸空气压缩机系列",
    nameEn: "MSA High-Pressure Breathing Air Compressor Series",
    summaryZh: "MSA 高压呼吸空气压缩机系列，用于高压呼吸空气充装和消防空气呼吸器配套服务。",
    summaryEn: "MSA high-pressure breathing air compressor series for breathing air filling and SCBA service support.",
    subcategoryZh: "呼吸空气压缩机",
    subcategoryEn: "Breathing air compressor",
    specs: "型号：MSA 250H、250HG、300H、300HG、200T、250T、300T、300TG、100TE、100TW、100TB\n压力：33MPa；排气量和功率以目录为准",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，高压呼吸空气压缩机页",
    imageSourceUrl: "docs/product-references/msa-safety/04-high-pressure-breathing-air-compressors.png",
    imageUrl: "/product-images/catalog-pages/msa/04-high-pressure-breathing-air-compressors.png"
  }),
  product({
    id: 77,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "M8-1800",
    nameZh: "MSA M8-1800 正压式消防空气呼吸器",
    nameEn: "MSA M8-1800 Firefighting SCBA",
    summaryZh: "MSA M8-1800 正压式消防空气呼吸器，适用于消防灭火和应急救援呼吸防护。",
    summaryEn: "MSA M8-1800 self-contained positive pressure air breathing apparatus for firefighting.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "相关 PN：10240493、10240494、10240495、10240496、10240497、10240498\n配置：6.8L/9L 30MPa 气瓶、G1 全面罩、500C 减压器等，以目录为准",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，M8-1800 页",
    imageSourceUrl: "docs/product-references/msa-safety/05-m8-1800-scba.png",
    imageUrl: "/product-images/catalog-pages/msa/05-m8-1800-scba.png"
  }),
  product({
    id: 78,
    categoryId: 7,
    brand: "MSA 梅思安",
    sku: "M8 / G1",
    nameZh: "MSA M8 正压式消防空气呼吸器与 G1 全面罩",
    nameEn: "MSA M8 Firefighting SCBA and G1 Full Facepiece",
    summaryZh: "MSA M8 正压式消防空气呼吸器，搭配 G1 全面罩和 IntelliHUD 压力平视显示装置。",
    summaryEn: "MSA M8 firefighting SCBA with G1 full facepiece and IntelliHUD pressure display options.",
    subcategoryZh: "正压式消防空气呼吸器",
    subcategoryEn: "SCBA",
    specs: "配置：G1 全面罩、IntelliHUD、人体工程背板、可旋转腰带、防水织布材料\n工作温度：-30°C 至 +60°C；防护等级 IP67",
    sourceUrl: "https://www.msasafety.com.cn/",
    sourceDocument: "MSA 梅思安综合样本，M8/G1 页",
    imageSourceUrl: "docs/product-references/msa-safety/06-m8-scba.png",
    imageUrl: "/product-images/catalog-pages/msa/06-m8-scba.png"
  })
];
